name: CI

on:
  push:
    branches: [ step2 ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Run Gateway in background
      run: |
        cd src/Gateway
        DOTNET_URLS=http://localhost:5080 dotnet run &
        sleep 5  # give it time to boot

    - name: Run Monolith in background
      run: |
        cd src/Monolith
        DOTNET_URLS=http://localhost:5070 dotnet run &
        sleep 5  # give it time to boot
    - name: Run Acceptance Tests
      run: |
        cd tests/AcceptanceTests
        dotnet test
